packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@eslint/js": ^9.38.0
  "@tailwindcss/postcss": ^4.1.16
  "@types/node": ^22.18.12
  eslint: ^9.38.0
  next: ^15.4.6
  prettier: ^3.6.2
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
  zod: ^4.1.12

catalogs:
  react19:
    "@types/react": ^19.1.12
    "@types/react-dom": ^19.1.9
    react: 19.1.1
    react-dom: 19.1.1

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@types/minimatch": 5.1.2

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
